#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

config = {
          'language': 'cs',
          'selector': '',
          'alpha': 5e-4,
          'randomize': True,
          'num_hidden_units': 128,
          'emb_size': 50,
          'batch_size': 20,
          'optimizer_type': 'adam',
          'max_cores': 4,
          'mode': 'tokens',
          'nn_type': 'emb_attention_seq2seq',
          'sort_da_emb': True,
          'cell_type': 'lstm',
          'dropout_keep_prob': 1,
          'use_dec_cost': False,
          'use_context': False,
          'use_div_token': False,
          'context_bleu_weight': 0,
          #'average_models': True,
          #'average_models_top_k': 3,

          'validation_size': 300,
          'validation_freq': 1,
          'validation_use_all_refs': True,
          'validation_use_train_refs': True,
          'validation_delex_slots': 'name,area,address,phone,good_for_meal,near,food,price_range,count,price,postcode',
          #'multiple_refs': '3,parallel',
          #'ref_selectors': 'ref0,ref1,ref2',
          'passes': 1000,
          'min_passes': 50,
          'improve_interval': 50,
          'top_k': 10,
          'bleu_validation_weight': 1,
          'beam_size': 20,
          'alpha_decay': 0, # 0.03

         'classif_filter': {
              'language': 'cs',
              'selector': '',
              #'nn': '1-hot',
              'nn': 'emb',
              #'nn_shape': 'ff1',
              'nn_shape': 'rnn',
              'num_hidden_units': 128,
              #'passes': 200,
              'passes': 100,
              'min_passes': 10,
              'randomize': True,
              'batch_size': 20,
              'alpha': 1e-3,
              'emb_size': 50,
              'max_tree_len': 50,
              'validation_freq': 1,
              'delex_slots': 'name,area,address,phone,good_for_meal,near,food,price_range,count,price,postcode',
              },

        'lexicalizer': {
            'form_select_type': 'random',
            'form_sample': False,
            'randomize': True,
            'passes': 50,
            'min_passes': 10,
            'alpha': 0.005,
            'alpha_decay': 0.0,
            'batch_size': 20,
            'max_sent_len': 32,
            'emb_size': 50,
            'cell_type': 'lstm',
            'max_grad_norm': 10,
            'optimizer_type': 'adam',
            'max_cores': 4,
        },
}
